apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
spec:
  serviceName: "mongo-service"
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:latest
        ports:
          - containerPort: 27017
        env:
          - name: MONGO_DATA_DIR
            value: /data/db

        volumeMounts:
          - name: mongo-volume-pvc
            mountPath: /data/db

  volumeClaimTemplates:
  - metadata:
      name: mongo-volume-pvc
    spec:
      volumeName: mongo-volume-ebs
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi