kind: "PersistentVolume"
apiVersion: "v1"
metadata:
  name: "mongo-volume-ebs" 
spec:
  capacity:
    storage: "10Gi" 
  storageClassName: gp2
  accessModes:
    - "ReadWriteOnce"
  awsElasticBlockStore: 
    fsType: "ext4" 
    volumeID: "vol-07047bfff8e41a17f" 
