version: "3"
services:

    movies-api:
        image: 'geekshubsdevops/movies-api:latest'
        container_name: 'movies-api'
        ports:
            - "3000:3000"
        environment: 
            MONGO_URL: 'mongo'
            MONGO_DATABASE: 'movies'

    # mongo:
    #     container_name: mongo
    #     image: mongo:latest
    #     environment:
    #         - MONGO_DATA_DIR=/data/db
    #         - MONGO_LOG_DIR=/dev/null
    #     volumes:
    #         - ../../data/db:/data/db

    master:
        image: locustio/locust
        ports:
        - "8089:8089"
        volumes:
        - ../../source/locust/benchmarks:/mnt/locust
        command: -f /mnt/locust/locustfile.py --master -H http://movies-api:3000
    
    worker:
        image: locustio/locust
        deploy:
            replicas: 8
        volumes:
        - ../../source/locust/benchmarks:/mnt/locust
        command: -f /mnt/locust/locustfile.py --worker --master-host master