version: "3"
services:

    movies-api:
        image: 'geekshubsdevops/movies-api:latest'
        container_name: 'movies-api'
        ports:
            - "3000:3000"
        environment: 
            MONGO_URL: 'mongo'
            MONGO_DATABASE: 'movies'

    mongo:
        container_name: mongo
        image: mongo:latest
        environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/dev/null
        volumes:
            - ../../data/db:/data/db
    
    master:
        image: 'christianbladescb/locustio'
        container_name: 'master'
        restart: always
        command: " -f locustfile.py --host=http://movies-api:3000 --master"
        ports:
        - "8089:8089"
        volumes:
        - ../../source/locust/benchmarks:/locust

    slave:
        image: 'christianbladescb/locustio'
        container_name: 'slave'
        restart: 'always'
        command: " -f locustfile.py --host=http://movies-api:3000 --slave --master-host=master"
        volumes:
        - ../../source/locust/benchmarks:/locust
